# See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions for docs

name: 'Setup my environment'
description: 'This is my reusable action'
author: 'Kristján Oddsson'
branding:
  icon: 'zap-off'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - id: valide-package-json
      run: npx --yes @koddsson/validate-pkg@latest
      shell: bash
